//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimerUtility.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TimerUtility.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;r&gt;
        ///  &lt;u p=&quot;1&quot; m=&quot;1&quot; ms=&quot;0&quot; o=&quot;1000&quot; s=&quot;1&quot; k=&quot;1&quot;/&gt;
        ///  &lt;h n=&quot;黄3&quot;&gt;
        ///    &lt;b n=&quot;圣母&quot; df=&quot;1&quot;&gt;
        ///      &lt;s n=&quot;减攻速&quot; d=&quot;280 仙224 魔235.2&quot; i=&quot;30&quot;/&gt;
        ///      &lt;s n=&quot;减吟唱&quot; d=&quot;175 仙140 魔147&quot; i=&quot;20&quot; a=&quot;群攻&quot;/&gt;
        ///      &lt;s n=&quot;群攻&quot; d=&quot;175 仙140 魔147&quot; i=&quot;20&quot; a=&quot;减吟唱&quot;/&gt;
        ///    &lt;/b&gt;
        ///    &lt;b n=&quot;小铁&quot;&gt;
        ///      &lt;s n=&quot;破甲&quot; d=&quot;320 仙256 魔268.8&quot; i=&quot;20&quot;/&gt;
        ///      &lt;s n=&quot;巨力&quot; d=&quot;200 仙160 魔168&quot; i=&quot;30&quot;/&gt;
        ///      &lt;s n=&quot;大群&quot; d=&quot;120 仙96 魔100.8&quot; i=&quot;20&quot;/&gt;
        ///    &lt;/b&gt;
        ///    &lt;b n=&quot;子纯&quot;&gt;
        ///      &lt;s n=&quot;封印&quot; d=&quot;450 仙360 魔378&quot; i=&quot;20&quot;/&gt;
        ///      &lt;s n=&quot;群晕&quot; d=&quot;300 仙240 魔252&quot; i=&quot;20&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string wmappdata {
            get {
                return ResourceManager.GetString("wmappdata", resourceCulture);
            }
        }
    }
}
